[tox]
envlist = lint, tests

[testenv]
basepython = python3
deps =
    -r{toxinidir}/requirements_test.txt

[testenv:lint]
deps =
    ruff
ignore_errors = True
commands =
    ruff check src tests
    ruff format --check src tests

[testenv:tests]
commands =
    pytest tests
