[tox]
envlist = lint, tests

[testenv]
basepython = python3
deps =
    -r{toxinidir}/requirements_test.txt

[testenv:lint]
deps =
    ruff
ignore_errors = True
commands =
    ruff check pycognito tests.py
    ruff format --check pycognito tests.py setup.py

[testenv:tests]
commands =
    pytest tests.py
