"""
MFAMixin — software token and SMS MFA setup, preferences, and challenge responses.

Kept in its own module because MFA flows are orthogonal to both the core
authentication path (auth.py) and user/group management (user_pool.py), and
are typically enabled or disabled as a unit.
"""


class MFAMixin:
    """Mixin providing MFA registration, preference management, and challenge responses."""

    # ------------------------------------------------------------------
    # Software token (TOTP)
    # ------------------------------------------------------------------

    def associate_software_token(self):
        """
        Begin TOTP setup — returns the secret code to seed an authenticator app.
        :return: Secret code string
        :rtype: str
        """
        response = self.client.associate_software_token(AccessToken=self.access_token)
        return response["SecretCode"]

    def verify_software_token(self, code, device_name=""):
        """
        Complete TOTP registration by verifying a generated code.
        :param code: The TOTP code generated by the authenticator app
        :param device_name: Optional friendly name for this device
        :return: True if verification succeeded
        :rtype: bool
        """
        response = self.client.verify_software_token(
            AccessToken=self.access_token,
            UserCode=code,
            FriendlyDeviceName=device_name,
        )
        return response["Status"] == "SUCCESS"

    # ------------------------------------------------------------------
    # MFA preference
    # ------------------------------------------------------------------

    def set_user_mfa_preference(self, sms_mfa, software_token_mfa, preferred=None):
        """
        Register the user's MFA preference.
        :param sms_mfa: Enable SMS MFA
        :type sms_mfa: bool
        :param software_token_mfa: Enable Software Token (TOTP) MFA
        :type software_token_mfa: bool
        :param preferred: "SMS" or "SOFTWARE_TOKEN", or None when both are disabled
        :type preferred: str or None
        """
        sms_mfa_settings = {"Enabled": bool(sms_mfa), "PreferredMfa": False}
        software_token_mfa_settings = {
            "Enabled": bool(software_token_mfa),
            "PreferredMfa": False,
        }
        if not (bool(sms_mfa) or bool(software_token_mfa)):
            # Disable all MFA — leave both PreferredMfa as False
            pass
        elif preferred == "SMS":
            sms_mfa_settings["PreferredMfa"] = True
        elif preferred == "SOFTWARE_TOKEN":
            software_token_mfa_settings["PreferredMfa"] = True
        else:
            raise ValueError(
                "preferred must have a value of 'SMS', 'SOFTWARE_TOKEN', or None."
            )
        self.client.set_user_mfa_preference(
            SMSMfaSettings=sms_mfa_settings,
            SoftwareTokenMfaSettings=software_token_mfa_settings,
            AccessToken=self.access_token,
        )

    # ------------------------------------------------------------------
    # MFA challenge responses
    # ------------------------------------------------------------------

    def respond_to_software_token_mfa_challenge(self, code, mfa_tokens=None):
        """
        Respond to a SOFTWARE_TOKEN_MFA challenge.
        :param code: The TOTP code from the authenticator app
        :type code: str
        :param mfa_tokens: Session tokens from MFAChallengeException.
            Optional if self.mfa_tokens is already set.
        """
        if not mfa_tokens:
            mfa_tokens = self.mfa_tokens
        challenge_responses = {
            "USERNAME": self.username,
            "SOFTWARE_TOKEN_MFA_CODE": str(code),
        }
        self._add_secret_hash(challenge_responses, "SECRET_HASH")
        tokens = self.client.respond_to_auth_challenge(
            ClientId=self.client_id,
            Session=mfa_tokens["Session"],
            ChallengeName="SOFTWARE_TOKEN_MFA",
            ChallengeResponses=challenge_responses,
        )
        self._set_tokens(tokens)

    def respond_to_sms_mfa_challenge(self, code, mfa_tokens=None):
        """
        Respond to an SMS_MFA challenge.
        :param code: The SMS OTP code
        :type code: str
        :param mfa_tokens: Session tokens from MFAChallengeException.
            Optional if self.mfa_tokens is already set.
        """
        if not mfa_tokens:
            mfa_tokens = self.mfa_tokens
        challenge_responses = {
            "USERNAME": self.username,
            "SMS_MFA_CODE": code,
        }
        self._add_secret_hash(challenge_responses, "SECRET_HASH")
        tokens = self.client.respond_to_auth_challenge(
            ClientId=self.client_id,
            Session=mfa_tokens["Session"],
            ChallengeName="SMS_MFA",
            ChallengeResponses=challenge_responses,
        )
        self._set_tokens(tokens)

    # ------------------------------------------------------------------
    # MFA configuration stubs
    # ------------------------------------------------------------------

    def admin_set_user_mfa_preference(
        self, username, sms_mfa, software_token_mfa, preferred=None
    ):
        """
        Admin-privilege version of set_user_mfa_preference — changes another
        user's MFA settings without their access token.
        Calls cognito-idp AdminSetUserMFAPreference.
        :param username: The user whose MFA preference to update.
        :param sms_mfa: Enable SMS MFA.
        :type sms_mfa: bool
        :param software_token_mfa: Enable Software Token MFA.
        :type software_token_mfa: bool
        :param preferred: "SMS", "SOFTWARE_TOKEN", or None if both are False.
        :type preferred: str or None
        :raises NotImplementedError:
        """
        raise NotImplementedError(
            "admin_set_user_mfa_preference is not yet implemented"
        )

    def get_user_pool_mfa_config(self, pool_id=None):
        """
        Return the pool-level MFA policy.
        Calls cognito-idp GetUserPoolMfaConfig.
        :param pool_id: The user pool ID. Defaults to self.user_pool_id.
        :return: MFA configuration dict.
        :raises NotImplementedError:
        """
        raise NotImplementedError("get_user_pool_mfa_config is not yet implemented")

    def set_user_pool_mfa_config(self, pool_id=None, **kwargs):
        """
        Set the pool-level MFA policy.
        Calls cognito-idp SetUserPoolMfaConfig.
        :param pool_id: The user pool ID. Defaults to self.user_pool_id.
        :param kwargs: SetUserPoolMfaConfig parameters (e.g. SmsMfaConfiguration,
            SoftwareTokenMfaConfiguration, MfaConfiguration).
        :raises NotImplementedError:
        """
        raise NotImplementedError("set_user_pool_mfa_config is not yet implemented")
